import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const alice = localFont({
  src: "./fonts/alice.ttf",
  variable: "--font-alice",
});

const heading = localFont({
  src: "./fonts/heading.ttf",
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${alice.variable} ${heading.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
